In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
x=[1,2,3,5,1,2]
nx=np.array(x)

In [5]:
print(nx)

[1 2 3 5 1 2]


In [6]:
nx.shape

(6,)

In [7]:
one = np.arange(1, 100, .2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [8]:
print(one.size)

495


In [9]:
two = np.linspace(0,100,200)
two

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [10]:
three = np.random.rand(100)
three

array([0.9477747 , 0.85164716, 0.01885034, 0.1184973 , 0.29247771,
       0.36771107, 0.66948285, 0.58499432, 0.87553554, 0.39658721,
       0.15716106, 0.18707273, 0.53573023, 0.87626109, 0.44252631,
       0.44050801, 0.51633156, 0.21397306, 0.76831223, 0.27140246,
       0.49617266, 0.79702663, 0.0601322 , 0.88396833, 0.49119943,
       0.58746716, 0.14755611, 0.50427689, 0.85620586, 0.47681881,
       0.45121057, 0.5762321 , 0.40523247, 0.40414313, 0.14940965,
       0.28806962, 0.23043095, 0.32947355, 0.66783999, 0.43361532,
       0.64550453, 0.18946212, 0.50135543, 0.46714441, 0.77120211,
       0.51600065, 0.00985732, 0.49342236, 0.84912836, 0.57998566,
       0.56680727, 0.22805036, 0.91364872, 0.23809136, 0.20258586,
       0.40553743, 0.77586067, 0.55232424, 0.14893625, 0.67382479,
       0.03131875, 0.55913906, 0.32208007, 0.17621021, 0.38538743,
       0.22447849, 0.48187088, 0.95514556, 0.73416948, 0.66279341,
       0.0684479 , 0.66094182, 0.97741659, 0.89956218, 0.90730

In [11]:
four = np.random.randint(1,10,100)
four

array([7, 9, 1, 7, 4, 2, 9, 8, 7, 6, 9, 2, 1, 6, 2, 2, 2, 2, 2, 2, 3, 4,
       2, 4, 3, 7, 2, 9, 4, 7, 6, 6, 9, 2, 4, 2, 1, 5, 8, 4, 5, 6, 8, 9,
       8, 9, 7, 1, 7, 2, 7, 5, 7, 2, 3, 2, 5, 9, 7, 1, 8, 5, 5, 8, 4, 8,
       8, 8, 3, 9, 7, 5, 3, 5, 8, 2, 3, 6, 3, 2, 2, 1, 1, 5, 9, 2, 9, 5,
       8, 4, 2, 2, 8, 2, 5, 9, 4, 1, 7, 4])

In [12]:
np.reshape(four, (10,10), order="F")


array([[7, 9, 3, 6, 5, 7, 8, 7, 2, 2],
       [9, 2, 4, 6, 6, 5, 5, 5, 1, 2],
       [1, 1, 2, 9, 8, 7, 5, 3, 1, 8],
       [7, 6, 4, 2, 9, 2, 8, 5, 5, 2],
       [4, 2, 3, 4, 8, 3, 4, 8, 9, 5],
       [2, 2, 7, 2, 9, 2, 8, 2, 2, 9],
       [9, 2, 2, 1, 7, 5, 8, 3, 9, 4],
       [8, 2, 9, 5, 1, 9, 8, 6, 5, 1],
       [7, 2, 4, 8, 7, 7, 3, 3, 8, 7],
       [6, 2, 7, 4, 2, 1, 9, 2, 4, 4]])

In [13]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))

In [14]:
n1+n2

array([[15,  8,  6,  7,  8],
       [13, 15, 10, 17,  4],
       [11, 12, 13, 12, 14],
       [10,  5, 11,  6,  9],
       [15, 12,  8,  5, 14]])

In [15]:
n1-n2

array([[-1,  4,  2, -5, -6],
       [-5,  1, -4, -1, -2],
       [-3, -4,  5,  6,  2],
       [-2, -1,  7, -4,  3],
       [-1,  0,  6,  3,  0]])

In [16]:
n1**4

array([[2401, 1296,  256,    1,    1],
       [ 256, 4096,   81, 4096,    1],
       [ 256,  256, 6561, 6561, 4096],
       [ 256,   16, 6561,    1, 1296],
       [2401, 1296, 2401,  256, 2401]], dtype=int32)

In [17]:
n1.dot(n2)

array([[152,  97,  75, 114, 101],
       [181, 118,  93, 146, 101],
       [249, 183,  98, 140, 177],
       [167, 133,  66,  80, 133],
       [239, 166,  99, 144, 170]])

In [18]:
n1*n2

array([[56, 12,  8,  6,  7],
       [36, 56, 21, 72,  3],
       [28, 32, 36, 27, 48],
       [24,  6, 18,  5, 18],
       [56, 36,  7,  4, 49]])

In [20]:
five=np.random.randint(1,10,10)

In [22]:
print(five)

[9 9 8 1 7 3 4 5 5 6]


In [23]:
z = np.array([[5,6,7,8],[1,3,5,5],[6,1,2,3]])
z

array([[5, 6, 7, 8],
       [1, 3, 5, 5],
       [6, 1, 2, 3]])

In [24]:
print(z[:2,1:3])

[[6 7]
 [3 5]]


In [25]:
five.sum(axis=0)

57

In [26]:
five.max()

9

the (argmax) Returns the indices of the maximum values along an axis.

In [28]:
five.argmax()

0

In [29]:
a = np.random.randint(1,10,(3,2))
b = np.random.randint(1,10,(3,2))
c = np.random.randint(1,10,(3,2))

In [30]:
print(a)
print(b)
print(c)

[[3 7]
 [1 3]
 [9 7]]
[[8 1]
 [8 6]
 [1 9]]
[[9 3]
 [2 2]
 [9 1]]


In [31]:
np.hstack((a,b))

array([[3, 7, 8, 1],
       [1, 3, 8, 6],
       [9, 7, 1, 9]])

In [32]:
np.vstack((a,b))

array([[3, 7],
       [1, 3],
       [9, 7],
       [8, 1],
       [8, 6],
       [1, 9]])

In [33]:
m = np.array([1,5,2,3,6,4,7,8,5,2,6,7,4,5,5,5,2,6,3,2,2])

In [35]:
print(m)

[1 5 2 3 6 4 7 8 5 2 6 7 4 5 5 5 2 6 3 2 2]


In [37]:
print(m>5)

[False False False False  True False  True  True False False  True  True
 False False False False False  True False False False]


In [38]:
print(m[m>5])

[6 7 8 6 7 6]


In [39]:
print(m[m != 5])

[1 2 3 6 4 7 8 2 6 7 4 2 6 3 2 2]


In [42]:
print(m[(m>2) & (m<6)])

[5 3 4 5 4 5 5 5 3]
